### ISSUE TITLE
Loading bam files

### ISSUE THREAD

**Issue by mhelena** [paul-shannon/igvShiny#3]
Hello Paul!
Thank you for this great idea! It is almost what I need!
I am trying to create IGV shiny widget on my app to visualise my bam files (whole exome data). 
Do you think it is possible to adapt your code for that?

**Comment by diegollarrull** [comment]
Hi, I hope it's not too late for it. 
I've actually made it work for .bam files. It is only needed to add a couple functions to igv.js and to igvShiny. 
Because of this, I can't make a PR since it overwrites igv.js code as well. 
But you can check out the modified version here: https://github.com/diegollarrull/igvShinyFork

**Comment by paul-shannon** [comment]
Hi @diegollarrull  - this looks great.  I will merge your changes into this repo.  
What changes to Jim Robinson's igv.js were needed?
@mhelena - so sorry!  I did not see your original issue, more than a year and a half ago.

**Comment by diegollarrull** [comment]
Hi @paul-shannon , just saw this message. The changes required in igv.js are described in [this](https://github.com/diegollarrull/igvShinyFork/commit/1f167c4d0bcd6a8794dcf579c7f1775fc84e9ec8) commit. 

Best regards

**Comment by yannickwurm** [comment]
Apologies - could you please clarify whether bam files can be loaded into igvShiny without @diegollarrull's modifications?
Thanks v mjuch
Yannick

**Comment by paul-shannon** [comment]
@yannickwurm   Yes, indeed.   With thanks to @diegollarrull, I added a few new track types to igvShiny, pushed them to github, package version 1.2.4.  Here's the result (for a 1000 genomes bam file) loaded via http:
![image](https://user-images.githubusercontent.com/2480712/97923463-e0056980-1d12-11eb-8d44-c6a44b33bfba.png)

**Comment by paul-shannon** [comment]
@yannickwurm   That image is from  the current version of ```inst/unitTests/igvShinyDemo.R``` in this repo

**Comment by yannickwurm** [comment]
That is very very cool!!

**Comment by paul-shannon** [comment]
I see that you (perhaps) work on ant genomics.  For the companion package, igvR, I just added code to simplify use of a genome not yet supported by Jim Robinson and his team.     See
```https://github.com/paul-shannon/igvR/blob/master/vignettes/chooseStockOrCustomGenome.Rmd```

I hope to consolidate these two packages, once the shiny developers enhance Shiny so that it does not lock down the console - promised for next summer.   But the igvR ```setCustomGenome``` method could be fitted into igvShiny, if there's a need.

**Comment by yannickwurm** [comment]
Ah thanks very much @paul-shannon  - that is indeed one of our key use cases. 
I now better understand the interplay between igvShiny and igvR.  Cheers!! (with hopeful thoughts for the election)
Yannick

**Comment by paul-shannon** [comment]
resolved
