### ISSUE TITLE
chromLocRegion reactive to change in selection 

### ISSUE THREAD

**Issue by heimannch** [paul-shannon/igvShiny#8]
Paul, thanks for the awesome work with this package! 
`igvShinyDemo.R` was enough to help me get started using this resource, but I ran into one use case that might involve functions that I am not aware of.

I am interested in storing the genomic region as a reactive object, and use this information to link IGV with other visualizations in my app.
The end result is similar to what in the `igvShinyDemo.R` app is achieved with the `getChrmLoc` button, but with `chromLocRegion` being reactive to any change in selection instead of being triggered by a button. I've tried to adapt the code related to `getChrmLoc`, such as:
```
    region_track <- reactive({
     printf("--- getChromLoc event")
     igvShiny::getGenomicRegion(session, id="igv_plot")
   })
   
   observeEvent(region_track(), {
     printf("--- currentGenomicRegion event")
     chromLocRegion <- input$currentGenomicRegion
     
     chromLocRegion
   })
```
but I had no success with that.

Alternatively, I see that I could also get this information updated if there is any way to listen to events linked to clicks of the magnifying glass at the IGV search bar.

Is there any way to implement either of these approaches?

**Comment by paul-shannon** [comment]
Hi @heimannch,

I've got a deadline tomorrow - happy to look at this once that  has passed, tomorrow afternoon.  Glad you find igvShiny helpful.    

(Possibly of interest: I now use this widget by wrapping it in an R6 class, much cleaner, I find, that raw shiny.  Not that this answers your immediate question, but if interested, you can see this here:  https://github.com/PriceLab/BioShiny/tree/master/igvWidget

**Comment by paul-shannon** [comment]
@heimannch,

Problem identified, fixed, demo updated.   Here is the event name to observe:
```
 observeEvent(input[[sprintf("currentGenomicRegion.%s", "igvShiny_0")]], {
    }
```
where, in this case (from ```igvShinyDemo.R```), we have just one igv instance, placed in a div with id ```igvShiny_0```.
A few months ago I refactored igvShiny so that multiple igv browsers can run independently in the same shiny app.  In javascript, the appropriate instance is identified by the id, supplied by the shiny app,  of the div into which it is rendered.  A bit clunky, but adequate for now.  

Please let me know if this makes sense, and works for you.
 - Paul

**Comment by heimannch** [comment]
Hi @paul-shannon,

Thanks for the quick follow up - and I hope everything went well with your deadline today!

After a quick look at the updated demo app, this is exactly what I was looking for. However, I am having some troubles implementing it in my app - the same code doesn't return the region. I believe it has to do with the fact that my app is a Shiny module and the id has a namespace. I will investigate this and let you know how it goes. 

Thanks!

**Comment by paul-shannon** [comment]
module namespaces - yep, that’s another wrinkle.  Before I gave up on modules, and for whatever it’s worth, I figured out actual element id mysteries like this in the javascript console.  

 - Paul

**Comment by heimannch** [comment]
Yes, I found some discussions of other packages that face similar challenges when used in shiny modules. (I found [this discussion](https://github.com/rstudio/shiny/issues/1081) very educational given my unfamiliarity with javascript)

I've organized `igvShinyDemo.R` as a module to figure out how to reference the id appropriately:
https://gist.github.com/heimannch/12e4f76bde5334ab189eebad0cd9f005
My latest attempt was to append the namespace to the id in the `sprintf` call - the resulting id is the same as the one I see in the javascript console, but no success yet in getting the selected region. If you have any suggestions of things to try, I would really appreciate it.

**Comment by paul-shannon** [comment]
@heimannch 
This should work now.  
I have not been shy about showing  my distaste for shiny modules - that feeling is now doubled!    Magic code operations which silently change explicit code, as modules do, is meant to help, but does not always do so.  Monkeying around with such basic and useful identifiers as div ids is a strange choice.   I admire almost everything coming out of RStudio.  But not modules.  Their lovely R6 class system, which I think emerged after modules, is a much simpler, much more elegant way to compose shiny apps.

But all my teeth gnashing is quite useless.   Shiny modules are probably here to stay.  So I cobbled together a fix, which you will find in version 1.2.8 of igvShiny, with your gist appearing now as inst/unitTests/igvShinyDemo-withModules.R

Here is how it works:

igvShiny.js now sends ```two``` events back to R since it cannot know if it is being hosted by a module or not:
```
Shiny.setInputValue("igv-currentGenomicRegion."+ htmlContainerID.replace("igv-", ""), chromLocString, {priority: "event"});
Shiny.setInputValue("currentGenomicRegion."+ htmlContainerID, chromLocString, {priority: "event"});
```
The actual name of the containing div, after namespaces are magically applied is```igv_igvShiny_1";  But the receiving shiny app (your code) expects the namespace to ```precede``` the event name.  So igvShiny.js now sends both messages back to R.
Note that the revised code only works in shiny modules with namespace "igv".  That is not sustainable, and if you have any igvShiny module with namespace id other than ```igv``` things will break.  

The solution is probably to pass the namespace id into the igvShiny constructor, defaulting to NA for non-module use.  I will mull this over. But these changes should get you back on the road for now.

**Comment by heimannch** [comment]
@paul-shannon, thanks so much for your attention to this issue!

Following your explanation of the changes, I updated a forked version of this repo with the namespace that is being used in my app, and, as you mentioned, I am back on the road now :)


> But all my teeth gnashing is quite useless.

Well, I personally found that very informative, for what it's worth. Please let me know if I can be of any help in eventual future changes of the package!

**Comment by paul-shannon** [comment]
> Please let me know if I can be of any help in eventual future changes of the package!

Your requests for fixes has already been very helpful.  More of them, or for new capabilities - all most welcome!

 - Paul
